version: "3.8"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    container_name: mysql-container
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: 'Asia/Tokyo'   